# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKJ3dMH3BpCPK1lAWoH1GiAPZtjc2sqN
"""

from google.colab import drive
drive.mount('/content/drive')

filename = '/content/drive/MyDrive/DS301_Final_Project/data/train_raw.tsv'
print(f"Loading from: {filename}")

import pandas as pd

# Adjusted column names (includes numeric index at start of file)
columns = [
    "index", "id", "label", "statement", "subject", "speaker", "speaker_job", "state_info",
    "party_affiliation", "barely_true_counts", "false_counts", "half_true_counts",
    "mostly_true_counts", "pants_on_fire_counts", "context", "justification"
]

# Load and process
df = pd.read_csv(filename, sep='\t', names=columns)

# Map to binary
label_mapping = {
    'pants-fire': 'False', 'FALSE': 'False', 'barely-true': 'False',
    'half-true': 'True', 'mostly-true': 'True', 'TRUE': 'True'
}

df['binary_label'] = df['label'].map(label_mapping)
binary_df = df[['id', 'statement', 'binary_label', 'subject', 'speaker']].dropna()

print(f"Dataset: {len(binary_df)} samples")
print(binary_df['binary_label'].value_counts())

# Save to Google Drive instead of downloading
binary_df.to_csv('/content/drive/MyDrive/DS301_Final_Project/data/liar_binary.csv', index=False)
print("Saved liar_binary.csv to Google Drive")

