# -*- coding: utf-8 -*-
"""newsapi_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1poEH907EeFGE8kk97e5nLFKcbnC1N9J3
"""

import requests
from typing import List, Dict

class NewsAPITool:
    def __init__(self, api_key: str = None, max_results: int = 2, max_chars: int = 300):
        self.api_key = api_key
        self.max_results = max_results
        self.max_chars = max_chars

    def search_evidence(self, claim: str) -> List[Dict[str, str]]:
        """Search news for evidence. Returns empty list if no API key."""
        if not self.api_key:
            return []  # Skip if no API key

        evidence = []
        try:
            url = "https://newsapi.org/v2/everything"
            params = {
                'q': claim,
                'sortBy': 'relevancy',
                'pageSize': self.max_results,
                'apiKey': self.api_key
            }

            response = requests.get(url, params=params, timeout=10)
            if response.status_code == 200:
                articles = response.json().get('articles', [])

                for article in articles:
                    title = article.get('title', '')
                    description = article.get('description', '')
                    content = f"{title}. {description}"

                    if len(content) > self.max_chars:
                        content = content[:self.max_chars] + "..."

                    evidence.append({
                        'source': f"News: {article.get('source', {}).get('name', 'Unknown')}",
                        'content': content
                    })

        except Exception as e:
            print(f"News API error: {e}")

        return evidence

