# -*- coding: utf-8 -*-
"""wikipedia_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yeFH-tvUNvxSjYnhzlx38Sl_58mbhyPR
"""


import wikipedia
from typing import List, Dict

class WikipediaTool:
    def __init__(self, max_results: int = 3, max_chars: int = 300):
        self.max_results = max_results
        self.max_chars = max_chars

    def search_evidence(self, claim: str) -> List[Dict[str, str]]:
        """Search Wikipedia for evidence related to the claim."""
        evidence = []

        try:
            # Extract key terms from claim for search
            search_terms = claim.replace('"', '').replace("'", '')
            results = wikipedia.search(search_terms, results=self.max_results)

            for title in results[:self.max_results]:
                try:
                    page = wikipedia.page(title)
                    summary = page.summary

                    if len(summary) > self.max_chars:
                        summary = summary[:self.max_chars] + "..."

                    evidence.append({
                        'source': f'Wikipedia: {title}',
                        'content': summary
                    })

                except (wikipedia.exceptions.DisambiguationError,
                        wikipedia.exceptions.PageError):
                    continue

        except Exception as e:
            print(f"Wikipedia search error: {e}")

        return evidence

